
spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/inventorydb
    username: root
    password: purboshi@123
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

